services:
  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: webapp
    volumes:
      - webapp_vol:/app/data
      - ./webapp:/app/webapp
    environment:
      - DB_BASE_DIR=app/data

    ports:
      - "8000:8000"
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 0.5G
    networks:
      - webapp_network

volumes:
  webapp_vol:

networks:
  webapp_network:
    driver: bridge
