services:
  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: webapp
    volumes:
      - webapp_vol:/app/data
      - ./webapp:/app/webapp
    environment:
      - DB_BASE_DIR=app/data

    ports:
      - "${WEBAPP_PORT}:${WEBAPP_PORT}"
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 0.5G
    networks:
      webapp_network:
        ipv4_address: ${WEBAPP_IP}

volumes:
  webapp_vol:

networks:
  webapp_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.19.0.0/16
